# 项目级 Gradle 配置
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
# Kotlin
kotlin.code.style=official
kotlin.incremental=true
# 决定是否使用 KSP（替代 KAPT）
ksp.useKSP=true
